id: c24e875f430e4df7aa118c2325083127
initial_creation_type: ocr
source_metadata:
  volumes:
    21bc75786c734f739e77235cf8d7f368:
      base_file: v061.txt
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      volume_number: 62
