id: DD3E75B51
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-13T03:41:03+00:00'
last_modified: '2022-05-27T09:57:20.952175+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4151':
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      order: 62
      base_file: 4151.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
